### PR TITLE
initial draft for balloon game

### PR DESCRIPTION
**Pull request by tyeung2017**
the game mechanism is ready. With hard-coded

pending:
make different colour of balloons and randomise the occurrence
randomise the blow up criteria of balloon according to balloon color

relates #11

### CODE REVIEW

**Review by Wyrd00 — APPROVED** [review]
🎆

**Comment by Karyum** [comment]
@KatiaAsh @Wyrd00 please review before i can review

**Review by KatiaAsh — APPROVED** [review]
:balloon:

**Comment by Karyum** [comment]
what is the purpose of this game?? what is it doing ?? what are the stats you are going to collect from it ?

**Comment by tyeung2017** [comment]
It is for testing the learning ability and risk averse of the user.

We do not include in code as intended.

as for the stats we haven't decided

@Karyum

**Review by Karyum — APPROVED** [review]

**Pull request merged**
