### PR TITLE
CSS for the balloon game

### PR DESCRIPTION
**Pull request by tyeung2017**
This is quite self-explanatory(?)

### CODE REVIEW

**Review by KatiaAsh — APPROVED** [review]
:birthday:

**Review by Karyum — APPROVED** [review]
@Wyrd00 merge it when you approve it

**Comment by tyeung2017** [comment]
shit 

mixed up the branches

**Comment by tyeung2017** [comment]
Revert to the QA approved version of PR. @Wyrd00 merge if there is no issues.

**Review by Wyrd00 — APPROVED** [review]
looks great!

**Pull request merged**
