### PR TITLE
translate landing page

### PR DESCRIPTION
**Pull request by KatiaAsh**
relate #8 #27 #28 #22 #6 #10

### CODE REVIEW

**Review by tyeung2017 — COMMENTED** [review]
Is it completed already?

**Comment by KatiaAsh** [comment]
@tyeung2017 Yes! :smile:

**Comment by tyeung2017** [comment]
@KatiaAsh Good job Katia!

Two more things:

1. Please merge with master for the updated game logic and push again, the version you pushed right now does not have that.

2. We want to have both English and Arabic version, so instead of replacing the English HTML files, you can copy them and place them with the Arabic version; Of course you need to rename the HTMLs.

Please amend and push again.

**Comment by KatiaAsh** [comment]
@tyeung2017 Thanks :relaxed: 
did you merge game logic?

**Pull request closed without merging**
