### PR TITLE
fix CSS and move drop down to nav bar

### PR DESCRIPTION
**Pull request by KatiaAsh**
fix CSS in general guideline AR and move drop down to the nav bar
relates #60

### CODE REVIEW

**Review by Wyrd00 — APPROVED** [review]

**Comment by KatiaAsh** [comment]
@tyeung2017 
PS: Drop down in result Ar doesn't work!
I'm trying to fix it

**Review by tyeung2017 — CHANGES_REQUESTED** [review]
CSS is missing in nav bar in result page 
And  move the dropdown to the top right corner in the landing

**Comment by tyeung2017** [comment]
Also wait for Amy's to get merge first, then @KatiaAsh MERGE WITH MASTER first and push again

**Comment by KatiaAsh** [comment]
@tyeung2017 
We didn't touch the CSS yet
and I'll MERGE WITH MASTER FIRST :fire:

**Review by tyeung2017 — APPROVED** [review]

**Comment by Karyum** [comment]
@KatiaAsh is this done ??

**Comment by Karyum** [comment]
ohh yeah sorry the labels misleaded me a bit

**Review by Karyum — APPROVED** [review]

**Pull request merged**
