### PR TITLE
Popup

### PR DESCRIPTION
**Pull request by Wyrd00**
Overlay for after the balloon game end

### CODE REVIEW

**Review by KatiaAsh — APPROVED** [review]
:100:

**Review by tyeung2017 — CHANGES_REQUESTED** [review]
Add logic to Arabic page as well

**Comment by tyeung2017** [comment]
Also make sure you change the number of balloons back to 10 or 20? after testing

**Comment by Wyrd00** [comment]
added and fixed, @tyeung2017 recheck

**Review by KatiaAsh — APPROVED** [review]

**Comment by tyeung2017** [comment]
you link to the English result page for the Arabic version 😄

**Comment by Wyrd00** [comment]
:woman_facepalming:

**Comment by tyeung2017** [comment]
Amy GO MERGE WITH MASTER FIRST 🤦‍♂️

**Comment by Wyrd00** [comment]
I did already brah

**Comment by Wyrd00** [comment]
oh darn, maybe not. PR slip through my radar :duck:

**Review by tyeung2017 — APPROVED** [review]

**Review by Karyum — APPROVED** [review]

**Pull request merged**
