### PR TITLE
Style drop down

### PR DESCRIPTION
**Pull request by KatiaAsh**
relates #62 #20 #23

### CODE REVIEW

**Review by tyeung2017 — COMMENTED** [review]
fancy

Btw can you position the drop in landing a bit to the top left

And seems this version messed up the css of the result page

**Comment by tyeung2017** [comment]
Good job @KatiaAsh 

But the color  for the traits page is not showing on my computer; does it work on yours?


Btw there are so many merge conflict right now, did you solve them?

**Comment by KatiaAsh** [comment]
Thanks :relaxed: @tyeung2017 

screenshot from 2017-10-09 22-51-44
screenshot from 2017-10-09 22-53-28
This how it's look like on my computer

I fix all the conflict :+1:

**Review by Wyrd00 — CHANGES_REQUESTED** [review]
Question - won't the dropdown styling be much better off in a separate css? If you wanted to change any css for the dropdown, you would have to labor and sift through all the css stylesheets... which doesn't seem efficient or effective.

**Comment by tyeung2017** [comment]
@KatiaAsh  

Good job for solving the conflict
There should be a background color in traits page.

Try to fix it with Amy.

**Comment by KatiaAsh** [comment]
@Wyrd00 Yes that makes more sense :heart:
I'm gonna make it now :smile: 

@tyeung2017 today me and @Wyrd00 we gonna work in styling :+1:

**Review by Wyrd00 — APPROVED** [review]
great job Katia!

**Review by tyeung2017 — APPROVED** [review]
Good job. 

After finishing all the CSS, work with Amy to build Arabic version of remaining pages

**Review by Karyum — APPROVED** [review]

**Pull request merged**
